image: python:3.7.6-slim

stages:
  - lint
  - test
  - deploy

before_script:
  - pip install --upgrade pip flake8

linting:
  stage: lint
  script:
    - flake8 src tests

test:
  stage: test
  dependencies:
    - linting
  before_script:
    - apt-get update && apt-get install -y
      build-essential
  script:
    - pip install -e ".[tests]"
    - pytest tests -s --cov src --cov-report term
  coverage: '/TOTAL.*\s(\d+)%/'

deploy:
  stage: deploy
  dependencies:
    - test
  script:
    - pip install -U setuptools wheel twine
    - python setup.py bdist_wheel sdist bdist_egg
    # XXX TWINE_PASSWORD and TWINE_USERNAME needs to be set
    - twine upload dist/*
  # when: manual
  only:
    - tags
