image: python:3.7.6-slim

stages:
  - lint
  - test

before_script:
  - pip install --upgrade pip flake8

linting:
  stage: lint
  script:
    - flake8 src tests

test:
  stage: test
  dependencies:
    - linting
  before_script:
    - apt-get update && apt-get install -y
      build-essential
  script:
    - pip install -e ".[tests]"
    - pytest tests -s --cov src --cov-report term
  coverage: '/TOTAL.*\s(\d+)%/'
